name: DeepL Mock Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of the repos DeepLcom/deepl-mock'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: DeepLcom/deepl-mock
        ref: ${{ github.event.inputs.tag }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/deepl-mock:latest,${{ secrets.DOCKERHUB_USERNAME }}/deepl-mock:${{ github.event.inputs.tag }}
